apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
  namespace: default
  labels:
    app: {{ .Values.serviceName }}-service
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: {{ .Values.containerPort }}
      port: 80
      protocol: TCP
  selector:
    app: {{ .Values.serviceName }}
