---
apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: fast-api # Name of the Kubernetes resource
  labels:
    app: fast-api
spec:
  replicas: 2 # Number of pods to run at any given time
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fast-api # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: fast-api
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: fast-api
          image: morheus/express:app1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Should match the port number that the your application listens on
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 5
            timeoutSeconds: 1
          livenessProbe: # To check the health of the Pod
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30
