apiVersion: v1
kind: Service # Type of kubernetes resource
metadata:
  name: fast-api-service # Name of the resource
  namespace: default
  labels:
    app: fast-api-service
spec:
  type: ClusterIP # A port is opened on each node in your cluster via Kube proxy.
  ports: # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      targetPort: 3000
      port: 80
      protocol: TCP
  selector:
    app: fast-api # Map any pod with label app=go-hello-world to this service
