nameSpace: default
application:
  repository: morheus/fast-api-app-from-git
  release: latest
  pullPolicy: IfNotPresent
  replicaCount: 2
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
  probes:
    readinessProbe:
      httpGet:
        path: /
        port: 80 #targetPort
        scheme: HTTP
      initialDelaySeconds: 20
      successThreshold: 5
      timeoutSeconds: 1
    livenessProbe:
      httpGet:
        path: /
        port: 80 #targetPort
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 5
  terminationGracePeriodSeconds: 60
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  ingressClassName: nginx
