name: DockerImageCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: private-registry-url
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD }}

      
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: docker build -t morheus /
           docker tag morheus:latest morheus/fast_api_app_from_git:app /
           docker push morheus/fast_api_app_from_git:app
  
