name: DockerImageCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      name: Login to DockerHub Registry
    - run: echo ${{ secrets.PASSWORD }} | docker login -u ${{ secrets.USERNAME }} --password-stdin
      
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: docker build -t morheus /
           docker tag morheus:latest morheus/fast_api_app_from_git:app /
           docker push morheus/fast_api_app_from_git:app
  
